<?php 
    return [
        'generated' => [1],
        'cancelled' => [3],
        'generated_form' => [5],
        'form_approval' => [6],
        'forms' => [5, 6],
        'form_issued' => [4],
        'form_approval_printing' => [4, 6],
        'liquidation_generated' => [7],
        'liquidation_approval' => [8],
        'liquidations' => [7, 8],
        'liquidation_cleared' => [9],
        'page_generated' => [1, 3],
        'page_form' => [5, 6, 4],
        'page_liquidation' => [7, 8, 9],
        'approver_form' => [1, 2],
        'approver_liquidation' => [1, 2],
        'unliquidated' => [1, 5, 6, 4, 7, 8],
        'deposit_type' => ['BANK', 'CHECK', 'ONLINE'],
        'issued_cleared' => [4, 9],
        'status' => [1, 3, 4, 5, 6, 7, 8, 9],
        'trans_types' => ['pr', 'po', 'pc'],
        'site_icon' => '/images/logo.png',
        'control_types' => ['Deposit Cash', 'Petty Cash', 'Online', 'Deposit Check'],
        'control_types_pc' => 'Petty Cash',
    ];