<?php 
    return [
        'admin_subadmin' => [1, 2],
        'generated' => [1],
        'form_generated' => [1, 5],
        'cancelled' => [3],
        'generated_form' => [5],
        'form_approval' => [6],
        'forms' => [5, 6],
        'form_issued' => [4],
        'form_approval_printing' => [4, 6],
        'liquidation_generated' => [7],
        'liquidation_approval' => [8],
        'liquidations' => [7, 8],
        'liquidation_cleared' => [9],
        'page_generated' => [1, 3],
        'page_form' => [5, 6, 4],
        'page_liquidation' => [7, 8, 9],
        'approver_form' => [1, 2],
        'approver_liquidation' => [1, 2],
        'unliquidated' => [1, 5, 6, 4, 7, 8],
        'deposit_type' => ['CHECK', 'ONLINE', 'CASH'],
        'issued_cleared' => [4, 9],
        'status' => [1, 3, 4, 5, 6, 7, 8, 9],
        'status_approval' => [6, 8],
        'currency' => ['PHP', 'USD', 'EUR'],
        'currency_label' => ['PHP', 'USD', 'EUR'],
        'trans_types' => ['pr', 'po', 'pc'],
        'site_icon' => '/images/logo.png',
        'site_banner' => '/images/banners/'.rand(1, 32).'.png',
        'control_types' => ['Cash', 'Check', 'Online'],
        'control_types_pc' => 'Petty Cash',
        'trans_category' => ['reg', 'dt', 'bp', 'hr', 'rb', 'bt'],
        'trans_category_column' => ['', 'is_deposit', 'is_bills', 'is_hr', 'is_reimbursement', 'is_bank'],
        'trans_category_column_2' => ['is_reg', 'is_deposit', 'is_bills', 'is_hr', 'is_reimbursement', 'is_bank'],
        'trans_category_label' => ['Regular Transaction', 'Deposit Transaction', 'Bills Payment', 'Salaries and Overhead Wages', 'Reimbursement', 'Fund Transfer'],
        'trans_category_label_filter' => ['All Categories', 'Deposit Transaction', 'Bills Payment', 'Salaries and Overhead Wages', 'Reimbursement', 'Fund Transfer'],
        'trans_category_label_filter_2' => ['All', 'Deposit Transaction', 'Bills Payment', 'Salaries and Overhead Wages', 'Reimbursement', 'Fund Transfer'],
        'trans_category_label_make_form' => ['Make Form', 'Make Form', 'Make Form', 'Make Form', 'Reimbursement', 'Fund Transfer'],
        'trans_category_label_edit_form' => ['Edit Form', 'Edit Form', 'Edit Form', 'Edit Form', 'Edit Reimbursement', 'Edit Fund Transfer'],
        'trans_category_label_create_liq' => ['Liquidate', 'Liquidate', 'Liquidate', 'Liquidate', 'Reimburse', 'Deposit Form'],
        'trans_category_label_liq_print' => ['Liquidation', 'Liquidation', 'Liquidation', 'Liquidation', 'Reimbursement', 'Deposit Form'],
        'status_filter' => [
            ['Generated', '1,5'],
            ['For Approval', '6'],
            ['Issued', '4'],
            ['Liq./For Approval', '7,8'],
            ['Cleared', '9'],
            ['Cancelled', '3'],
        ],
        'status_filter_reports' => [
            ['Generated', '1'],
            ['Form/Generated', '5'],
            ['For Approval', '6'],
            ['Issued', '4'],
            ['Liq./Generated', '7'],
            ['Liq./For Approval', '8'],
            ['Cleared', '9'],
            ['Cancelled', '3'],
        ],
        'status_checkpoint' => [
            '5' => ['1'],
            '6' => ['5', '1'],
            '4' => ['6', '5', '1'],
            '7' => ['4', '6', '5', '1'],
            '8' => ['7', '4', '6', '5', '1'],
            '9' => ['8', '7', '4', '6', '5', '1'],
        ],
        'attachment_format' => ['jpg', 'jpeg', 'png', 'pdf'],
        'apps' => ['leaves', 'sequence', 'people', 'resources', 'travels'],
        'dashboard_sequence' => '/sequence-dashboard',
        'dashboard_leaves' => '/leaves-dashboard',
        'dashboard_people' => '/people-dashboard',
        'dashboard_resources' => '/resources-dashboard',
        'dashboard_travels' => '/travels-dashboard',
        'site_colors' => [
            'blue',
            'indigo',
            'purple',
            'pink',
            'red',
            'orange',
            'yellow',
            'green',
            'teal',
            'cyan',
        ],
        'category_colors' => [
            ['Regular', 'yellow'],
            ['Deposit', 'green'],
            ['Bills', 'blue'],
            ['HR', 'violet'],
            ['Reimbursement', 'red'],
            ['Fund', 'Purple'],
        ],
        'gender' => ['Male', 'Female'],
        'civil_status' => ['Single', 'Married', 'Widowed', 'Separated'],
        'employment_status' => ['Regular', 'Probationary'],
        'is_yesno_id' => ['1', '5'],
        'ua_none' => '5',
        'ua_own' => '2',
        'ua_inactive' => '6',
        'ua_trans_view_conf' => '58',
        'hidden_route_option' => ['trans_toggle_conf_own'],
        'leaves_link' => 'https://docs.google.com/forms/d/e/1FAIpQLSdmvYUWmgQWug6MZ3uuSIvHVLPKVpmZlca31oexwktG3OfDvQ/viewform?embedded=true',
        'issue_attachment_note' => "If CHECK, upload the check copy and deposit slip.<br>If UB ONLINE, upload the UB confirmation payment.",
        'issue_attachment_note_2' => "Only one(1) document can be uploaded. A Zip file or a pdf document containing multiple attachments are accepted.",
        'travel_role_id_admin' => '1',
        'travel_role_id_reviewer' => '2',
        'travel_role_id_approver' => '3',
        'travel_role_id_booker' => '4',
        'travel_status_id_generated' => '1',
        'travel_status_id_for_review' => '2',
        'travel_status_id_for_approval' => '3',
        'travel_status_id_for_booking' => '4',
        'travel_status_id_booked' => '5',
        'travel_status_id_cancelled' => '6',
        'travel_attachment_types' => ['others', 'hotel', 'flight'],
    ];